# Generated by Django 4.2.3 on 2023-07-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'тэг статьи', 'verbose_name_plural': 'Тэги статьи'},
        ),
    ]
